In [34]:
import cymetric as cym
from cymetric import convenient_interface as cin

In [35]:
db = cym.dbopen('cyclus.sqlite')

In [36]:
fuel_trans_tot = cin.GetTransactionTimeSeries(db, receiver='FBR_driver')
fuel_trans_tot

      Quantity
Time
3       4145.0
5       4145.0
7       4145.0
25      4145.0
43      4145.0
61      4145.0
79      4145.0
97      4145.0
115     4145.0
133     4145.0
151     4145.0
169     4145.0
187     4145.0
205     4145.0
223     4145.0
241     4145.0
259     4145.0
277     4145.0
295     4145.0
313     4145.0
331     4145.0
349     4145.0
367     4145.0
385     4145.0
403     4145.0
421     4145.0
439     4145.0
457     4145.0
475     4145.0
493     4145.0
...        ...
691     4145.0
709     4145.0
727     4145.0
745     4145.0
763     4145.0
781     4145.0
799     4145.0
817     4145.0
835     4145.0
853     4145.0
871     4145.0
889     4145.0
907     4145.0
925     4145.0
943     4145.0
957     4145.0
959     4145.0
961     4145.0
979     4145.0
997     4145.0
1015    4145.0
1033    4145.0
1051    4145.0
1069    4145.0
1087    4145.0
1105    4145.0
1123    4145.0
1141    4145.0
1159    4145.0
1177    4145.0

[70 rows x 1 columns]

In [37]:
fuel_trans_pu = cin.GetTransactionTimeSeries(db, 'FBR_driver_fabrication', 'FBR_driver', 'pu238','pu239','pu240','pu241','pu242')

In [38]:
fuel_inv =cin.GetInventoryTimeSeries(db, 'FBR_driver_fabrication')
fuel_inv

                             Quantity
Prototype              Time
FBR_driver_fabrication 2       4210.0
                       3         65.0
                       4       4210.0
                       5         65.0
                       6       4210.0
                       7         65.0
                       8       4210.0
                       9       4210.0
                       10      4210.0
                       11      4210.0
                       12      4210.0
                       13      4210.0
                       14      4210.0
                       15      4210.0
                       16      4210.0
                       17      4210.0
                       18      4210.0
                       19      4210.0
                       20      4210.0
                       21      4210.0
                       22      4210.0
                       23      4210.0
                       24      4210.0
                       25        65.0
                       26      4210.0
                       27      4210.0
                       28      4210.0
                       29      4210.0
                       30      4210.0
                       31      4210.0
...                               ...
                       1170    4210.0
                       1171    4210.0
                       1172    4210.0
                       1173    4210.0
                       1174    4210.0
                       1175    4210.0
                       1176    4210.0
                       1177      65.0
                       1178    4210.0
                       1179    4210.0
                       1180    4210.0
                       1181    4210.0
                       1182    4210.0
                       1183    4210.0
                       1184    4210.0
                       1185    4210.0
                       1186    4210.0
                       1187    4210.0
                       1188    4210.0
                       1189    4210.0
                       1190    4210.0
                       1191    4210.0
                       1192    4210.0
                       1193    4210.0
                       1194    4210.0
                       1195    4210.0
                       1196    4210.0
                       1197    4210.0
                       1198    4210.0
                       1199    4210.0

[1198 rows x 1 columns]

In [41]:
fuel_trans_pu_frac

      Quantity
Time
3     0.109422
21    0.109422
39    0.109422
57    0.109422
75    0.109422
93    0.109422
111   0.109422
129   0.109422
147   0.109422
165   0.109422
183   0.109422
201   0.109422
219   0.109422
237   0.109422
255   0.109422
273   0.109422
291   0.109422
309   0.109422
327   0.109422
345   0.109422
363   0.109422
381   0.109422
399   0.109422
417   0.109422
435   0.109422
453   0.109422
471   0.109422
489   0.109422
507   0.109422
525   0.109422
...        ...
669   0.109422
687   0.109422
705   0.109422
723   0.109422
741   0.109422
759   0.109422
777   0.109422
795   0.109422
813   0.109422
831   0.109422
849   0.109422
867   0.109422
885   0.109422
903   0.109422
921   0.109422
939   0.109422
957   0.109422
975   0.109422
993   0.109422
1011  0.109422
1029  0.109422
1047  0.109422
1065  0.109422
1083  0.109422
1101  0.109422
1119  0.109422
1137  0.109422
1155  0.109422
1173  0.109422
1191  0.109422

[67 rows x 1 columns]

In [39]:
E2 = cin.GetTransactionTimeSeries(db, receiver='FBR_driver_fabrication', sender='Storage_E1_second')

In [40]:
E2

         Quantity
Time
2     3310.000000
4     3301.593424
6     3301.593424
8     3301.593424
26    3301.593424
44    3301.593424
62    3301.593424
80    3301.593424
98    3301.593424
116   3301.593424
134   3301.602646
152   3301.598483
170   3301.602975
188   3301.607723
206   3301.598814
224   3301.602996
242   3301.607725
260   3301.608033
278   3301.682249
296   3301.524828
314   3301.602816
332   3301.607725
350   3301.608033
368   3301.682249
386   3301.608241
404   3301.608055
422   3301.524634
440   3301.602815
458   3301.607725
476   3301.682229
...           ...
692   3301.608054
710   3301.608054
728   3301.608054
746   3301.682250
764   3301.608241
782   3301.608055
800   3301.608054
818   3301.608054
836   3301.608054
854   3301.524634
872   3301.602815
890   3301.607725
908   3301.682229
926   3301.608239
944   3301.608055
958   3301.608054
960   3301.608054
962   3301.608054
980   3301.608054
998   3301.608054
1016  3301.608054
1034  3301.608054
1052  3301.682250
1070  3301.608241
1088  3301.608055
1106  3301.608054
1124  3301.608054
1142  3301.608054
1160  3301.524634
1178  3301.602815

[71 rows x 1 columns]